package sergionsz.daily

object EmojiSearchData {
    data class Entry(val emoji: String, val keywords: List<String>)

    val entries: List<Entry> = listOf(
        Entry("😀", listOf("smile", "happy", "grin", "face")),
        Entry("😃", listOf("smile", "happy", "grin", "joy")),
        Entry("😄", listOf("smile", "happy", "laugh", "joy")),
        Entry("😁", listOf("smile", "grin", "happy")),
        Entry("😆", listOf("laugh", "haha", "funny")),
        Entry("😅", listOf("laugh", "sweat", "relief")),
        Entry("😂", listOf("laugh", "lol", "tears", "joy")),
        Entry("🤣", listOf("rofl", "laugh", "rolling")),
        Entry("😊", listOf("smile", "blush", "happy")),
        Entry("🙂", listOf("smile", "slight", "happy")),
        Entry("😉", listOf("wink", "flirt")),
        Entry("😍", listOf("love", "heart", "eyes", "crush")),
        Entry("🥰", listOf("love", "hearts", "blush")),
        Entry("😘", listOf("kiss", "love")),
        Entry("😎", listOf("cool", "sunglasses", "boss")),
        Entry("🤓", listOf("nerd", "geek", "study")),
        Entry("🥳", listOf("party", "celebrate", "birthday")),
        Entry("😢", listOf("cry", "sad", "tear")),
        Entry("😭", listOf("cry", "sob", "sad", "tears")),
        Entry("😡", listOf("angry", "mad", "rage")),
        Entry("😱", listOf("scream", "shock", "fear")),
        Entry("🤔", listOf("think", "thinking", "ponder")),
        Entry("😴", listOf("sleep", "tired", "zzz")),
        Entry("💤", listOf("sleep", "zzz", "tired")),
        Entry("🤒", listOf("sick", "ill", "fever")),
        Entry("🤕", listOf("hurt", "injured", "bandage")),
        Entry("🥶", listOf("cold", "freezing")),
        Entry("🥵", listOf("hot", "heat", "sweat")),
        Entry("👍", listOf("thumbs", "up", "yes", "approve", "like")),
        Entry("👎", listOf("thumbs", "down", "no", "dislike")),
        Entry("👌", listOf("ok", "okay", "perfect")),
        Entry("👏", listOf("clap", "applause", "bravo")),
        Entry("🙌", listOf("hands", "celebrate", "praise")),
        Entry("🙏", listOf("pray", "thanks", "please")),
        Entry("✋", listOf("hand", "stop", "high", "five")),
        Entry("🤝", listOf("handshake", "deal", "agree")),
        Entry("💪", listOf("muscle", "strong", "flex", "workout", "gym")),
        Entry("🧠", listOf("brain", "smart", "think", "study", "mind")),
        Entry("👀", listOf("eyes", "look", "see")),
        Entry("❤️", listOf("heart", "love", "red")),
        Entry("🧡", listOf("heart", "orange", "love")),
        Entry("💛", listOf("heart", "yellow", "love")),
        Entry("💚", listOf("heart", "green", "love")),
        Entry("💙", listOf("heart", "blue", "love")),
        Entry("💜", listOf("heart", "purple", "love")),
        Entry("🖤", listOf("heart", "black", "love")),
        Entry("🤍", listOf("heart", "white", "love")),
        Entry("💔", listOf("heart", "broken", "sad")),
        Entry("💕", listOf("hearts", "love")),
        Entry("✨", listOf("sparkle", "shine", "star", "magic")),
        Entry("⭐", listOf("star", "favorite")),
        Entry("🌟", listOf("star", "glowing", "shine")),
        Entry("💫", listOf("dizzy", "star", "sparkle")),
        Entry("🔥", listOf("fire", "hot", "lit", "flame")),
        Entry("⚡", listOf("lightning", "bolt", "fast", "energy")),
        Entry("💥", listOf("boom", "explosion", "collision")),
        Entry("🎯", listOf("target", "goal", "bullseye", "aim")),
        Entry("🏆", listOf("trophy", "win", "champion", "award")),
        Entry("🥇", listOf("gold", "first", "medal", "win")),
        Entry("🎉", listOf("party", "celebrate", "popper")),
        Entry("🎊", listOf("confetti", "party", "celebrate")),
        Entry("🎁", listOf("gift", "present", "box")),
        Entry("🎂", listOf("cake", "birthday", "celebrate")),
        Entry("✅", listOf("check", "done", "complete", "yes")),
        Entry("❌", listOf("cross", "no", "wrong", "fail")),
        Entry("✔️", listOf("check", "done", "yes", "tick")),
        Entry("☑️", listOf("checkbox", "done", "yes")),
        Entry("💡", listOf("idea", "light", "bulb", "think", "tip")),
        Entry("📌", listOf("pin", "important", "note")),
        Entry("📍", listOf("location", "pin", "place")),
        Entry("🔖", listOf("bookmark", "tag", "save")),
        Entry("🏃", listOf("run", "running", "exercise", "jog")),
        Entry("🚶", listOf("walk", "walking")),
        Entry("🧘", listOf("yoga", "meditate", "zen", "calm")),
        Entry("🚴", listOf("bike", "cycle", "cycling", "bicycle")),
        Entry("🏊", listOf("swim", "swimming", "pool")),
        Entry("🏋️", listOf("lift", "weight", "gym", "workout")),
        Entry("🤸", listOf("cartwheel", "exercise", "active")),
        Entry("⚽", listOf("soccer", "football", "ball")),
        Entry("🏀", listOf("basketball", "ball", "sport")),
        Entry("🎾", listOf("tennis", "ball", "sport")),
        Entry("🥊", listOf("boxing", "glove", "fight")),
        Entry("🎮", listOf("game", "gaming", "controller")),
        Entry("🎲", listOf("dice", "game", "roll")),
        Entry("🎵", listOf("music", "note", "song")),
        Entry("🎶", listOf("music", "notes", "song")),
        Entry("🎧", listOf("headphones", "music", "listen")),
        Entry("🎸", listOf("guitar", "music", "rock")),
        Entry("🎹", listOf("piano", "music", "keys")),
        Entry("📚", listOf("books", "read", "reading", "study", "learn")),
        Entry("📖", listOf("book", "read", "open")),
        Entry("✍️", listOf("write", "writing", "journal", "pen")),
        Entry("✏️", listOf("pencil", "write", "edit")),
        Entry("📝", listOf("note", "memo", "write", "list")),
        Entry("💻", listOf("laptop", "computer", "code", "work")),
        Entry("🖥️", listOf("computer", "desktop", "monitor")),
        Entry("📱", listOf("phone", "mobile", "smartphone")),
        Entry("⌨️", listOf("keyboard", "type")),
        Entry("📅", listOf("calendar", "date", "schedule")),
        Entry("📆", listOf("calendar", "date", "schedule")),
        Entry("⏰", listOf("alarm", "clock", "time", "wake")),
        Entry("⏱️", listOf("stopwatch", "timer", "time")),
        Entry("⏳", listOf("hourglass", "wait", "time")),
        Entry("💧", listOf("water", "drop", "drink", "hydrate")),
        Entry("🥤", listOf("drink", "cup", "soda")),
        Entry("☕", listOf("coffee", "tea", "drink", "hot")),
        Entry("🍵", listOf("tea", "drink", "matcha")),
        Entry("🧃", listOf("juice", "drink", "box")),
        Entry("🍎", listOf("apple", "fruit", "red", "healthy")),
        Entry("🍌", listOf("banana", "fruit", "yellow")),
        Entry("🍊", listOf("orange", "fruit", "citrus")),
        Entry("🍓", listOf("strawberry", "fruit", "berry")),
        Entry("🥗", listOf("salad", "healthy", "food", "veggie")),
        Entry("🥦", listOf("broccoli", "veggie", "healthy")),
        Entry("🍞", listOf("bread", "food")),
        Entry("🍕", listOf("pizza", "food", "slice")),
        Entry("🍔", listOf("burger", "hamburger", "food")),
        Entry("🍣", listOf("sushi", "food", "japanese")),
        Entry("🍿", listOf("popcorn", "movie", "snack")),
        Entry("🍫", listOf("chocolate", "candy", "sweet")),
        Entry("🍩", listOf("donut", "doughnut", "sweet")),
        Entry("🚿", listOf("shower", "wash", "clean")),
        Entry("🛁", listOf("bath", "tub", "wash")),
        Entry("🦷", listOf("tooth", "brush", "teeth", "dental")),
        Entry("🧴", listOf("lotion", "soap", "shampoo", "bottle")),
        Entry("🧼", listOf("soap", "wash", "clean")),
        Entry("🧹", listOf("broom", "clean", "sweep")),
        Entry("🧺", listOf("laundry", "basket")),
        Entry("🛏️", listOf("bed", "sleep", "rest")),
        Entry("🌱", listOf("plant", "seedling", "grow", "nature")),
        Entry("🌿", listOf("herb", "plant", "leaf", "nature")),
        Entry("🌳", listOf("tree", "nature", "park")),
        Entry("🌷", listOf("tulip", "flower", "spring")),
        Entry("🌸", listOf("blossom", "flower", "spring", "pink")),
        Entry("🌻", listOf("sunflower", "flower")),
        Entry("🌞", listOf("sun", "sunshine", "day", "bright")),
        Entry("🌙", listOf("moon", "night", "crescent")),
        Entry("☁️", listOf("cloud", "weather", "sky")),
        Entry("🌧️", listOf("rain", "weather", "shower")),
        Entry("❄️", listOf("snow", "snowflake", "cold", "winter")),
        Entry("🐶", listOf("dog", "puppy", "pet")),
        Entry("🐱", listOf("cat", "kitty", "pet")),
        Entry("🐰", listOf("rabbit", "bunny", "pet")),
        Entry("🐸", listOf("frog", "animal")),
        Entry("🦋", listOf("butterfly", "insect", "nature")),
        Entry("🐝", listOf("bee", "insect", "honey")),
        Entry("🏠", listOf("home", "house", "house")),
        Entry("🏢", listOf("office", "building", "work")),
        Entry("🏥", listOf("hospital", "medical", "health")),
        Entry("🚗", listOf("car", "auto", "drive")),
        Entry("✈️", listOf("plane", "fly", "travel")),
        Entry("💰", listOf("money", "bag", "cash")),
        Entry("💵", listOf("money", "dollar", "cash")),
        Entry("💳", listOf("card", "credit", "pay")),
        Entry("📞", listOf("phone", "call", "telephone")),
        Entry("📧", listOf("email", "mail", "message")),
        Entry("💬", listOf("chat", "speech", "talk")),
        Entry("🎨", listOf("art", "paint", "palette", "draw")),
        Entry("🖌️", listOf("brush", "paint", "art")),
        Entry("📷", listOf("camera", "photo", "picture")),
        Entry("🎬", listOf("movie", "film", "clapper")),
        Entry("🎤", listOf("mic", "microphone", "sing"))
    )

    fun search(query: String): List<String> {
        val q = query.lowercase().trim()
        if (q.isEmpty()) return emptyList()
        return entries.filter { entry ->
            entry.keywords.any { it.startsWith(q) || it.contains(q) }
        }.map { it.emoji }
    }
}
